# Generated by Django 2.2.3 on 2019-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_reg',
            name='status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
