# Generated by Django 2.2.3 on 2019-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tbl_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booked_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=50)),
                ('booked_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
