# Generated by Django 2.2.3 on 2019-09-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_booked_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_booked_item',
            new_name='tbl_booked_items',
        ),
    ]
