# Generated by Django 2.2.3 on 2019-09-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20190915_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booked_items',
        ),
    ]
