# Generated by Django 2.2.3 on 2019-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='item_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
