# Generated by Django 2.2.3 on 2019-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_tbl_booking_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=50)),
                ('booking_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
