# Generated by Django 2.2.3 on 2019-09-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_tbl_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
